<?php

declare(strict_types=1);

return [
    'catalog' => [
        'companies.view' => ['Companies: View', 'companies', false],
        'companies.manage' => ['Companies: Manage Own', 'companies', false],
        'branches.view' => ['Branches: View', 'branches', false],
        'branches.manage' => ['Branches: Manage', 'branches', false],
        'users.view' => ['Users: View', 'users', false],
        'users.manage' => ['Users: Manage', 'users', false],
        'roles.view' => ['Roles: View', 'roles', false],
        'roles.manage' => ['Roles: Manage', 'roles', false],
        'customers.view' => ['Customers: View', 'customers', false],
        'customers.manage' => ['Customers: Manage', 'customers', false],
        'shipments.view' => ['Shipments: View', 'shipments', false],
        'shipments.manage' => ['Shipments: Manage', 'shipments', false],
        'batches.view' => ['Batches: View', 'batches', false],
        'batches.manage' => ['Batches: Manage', 'batches', false],
        'tracking.view' => ['Tracking: View', 'tracking', false],
        'tracking.update' => ['Tracking: Update', 'tracking', false],
        'packages.scan' => ['Packages: Scan', 'warehouse', false],
        'warehouses.view' => ['Warehouses: View', 'warehouses', false],
        'warehouses.manage' => ['Warehouses: Manage', 'warehouses', false],
        'warehouse.receive' => ['Warehouse: Receive', 'warehouse', false],
        'warehouse.dispatch' => ['Warehouse: Dispatch', 'warehouse', false],
        'containers.view' => ['Containers: View', 'freight', false],
        'containers.manage' => ['Containers: Manage', 'freight', false],
        'flights.view' => ['Flights: View', 'freight', false],
        'flights.manage' => ['Flights: Manage', 'freight', false],
        'vessels.view' => ['Vessels: View', 'freight', false],
        'vessels.manage' => ['Vessels: Manage', 'freight', false],
        'manifests.view' => ['Manifests: View', 'freight', false],
        'manifests.manage' => ['Manifests: Manage', 'freight', false],
        'customs.view' => ['Customs: View', 'customs', false],
        'customs.manage' => ['Customs: Manage', 'customs', false],
        'deliveries.view' => ['Deliveries: View', 'delivery', false],
        'deliveries.manage' => ['Deliveries: Manage', 'delivery', false],
        'deliveries.execute' => ['Deliveries: Execute Assigned', 'delivery', false],
        'drivers.view' => ['Drivers: View', 'delivery', false],
        'drivers.manage' => ['Drivers: Manage', 'delivery', false],
        'vehicles.view' => ['Vehicles: View', 'delivery', false],
        'vehicles.manage' => ['Vehicles: Manage', 'delivery', false],
        'agents.view' => ['Agents: View', 'agents', false],
        'agents.manage' => ['Agents: Manage', 'agents', false],
        'rates.view' => ['Rates: View', 'billing', false],
        'rates.manage' => ['Rates: Manage', 'billing', false],
        'billing.view' => ['Billing: View', 'billing', false],
        'billing.manage' => ['Billing: Manage', 'billing', false],
        'payments.view' => ['Payments: View', 'billing', false],
        'payments.manage' => ['Payments: Manage', 'billing', false],
        'reports.view' => ['Reports: View', 'reports', false],
        'reports.export' => ['Reports: Export', 'reports', false],
        'notifications.view' => ['Notifications: View', 'notifications', false],
        'notifications.manage' => ['Notifications: Manage', 'notifications', false],
        'audit-logs.view' => ['Audit Logs: View', 'audit', false],
        'statuses.view' => ['Shipment Statuses: View', 'settings', false],
        'statuses.manage' => ['Shipment Statuses: Manage', 'settings', false],
        'webhooks.view' => ['Webhooks: View', 'integrations', false],
        'webhooks.manage' => ['Webhooks: Manage', 'integrations', false],
        'system-configuration.manage' => ['System Configuration: Manage', 'platform', true],
        'platform-companies.manage' => ['Platform Companies: Manage', 'platform', true],
        'failed-jobs.manage' => ['Failed Jobs: Manage', 'platform', true],
    ],
];
